import { Link } from 'react-router-dom';

import type { Article } from '../types';

interface HeadlineStoryProps {
  story: Article;
}

export default function HeadlineStory({ story }: HeadlineStoryProps) {
  return (
    <article className="headline-story">
      <Link to={`/article/${story.slug}`}>
        <div className="headline-image-wrapper">
          <img className="headline-image" src={story.image_url} alt={story.image_alt} />
        </div>
      </Link>
      <Link to={`/article/${story.slug}`}>
        <h2 className="headline-title">{story.headline}</h2>
      </Link>
      <p className="headline-subtitle">{story.subheadline}</p>
      <div
        className="headline-body"
        // The body is satirical HTML written by Nigel; it's only ever generated by
        // our backend pipeline and is sanitised at insert time, so it's safe to render.
        dangerouslySetInnerHTML={{ __html: story.body_html }}
      />
      {story.source ? (
        <p className="story-source">
          inspired by{' '}
          <span className="source-outlet">{story.source.outlet}</span>
        </p>
      ) : null}
    </article>
  );
}
